language: generic
services:
- docker
jobs:
  include:
    - stage: build-and-test
      script:
        - docker build --target=build -t languagetool-build .
        - docker run languagetool-build mvn clean test --quiet
    - stage: pre-release
      if: tag =~ ^v[0-9]+\.[0-9]+(?:\.[0-9]+)?-((?!dockerupdate-[0-9]+).)*$
      script:
        - DOCKER_TAG=$(echo $TRAVIS_TAG | grep -oP '(?<=v).*')
        - docker build -t $DOCKER_USERNAME/languagetool:$DOCKER_TAG .
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker push $DOCKER_USERNAME/languagetool:$DOCKER_TAG
    - stage: release
      if: tag =~ ^v[0-9]+\.[0-9]+(?:\.[0-9]+)?(?:-dockerupdate-[0-9]+)?$
      script:
        - DOCKER_TAG=$(echo $TRAVIS_TAG | grep -oP '(?<=v).*')
        - docker build -t $DOCKER_USERNAME/languagetool:$DOCKER_TAG -t $DOCKER_USERNAME/languagetool:latest .
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker push $DOCKER_USERNAME/languagetool:$DOCKER_TAG
        - docker push $DOCKER_USERNAME/languagetool:latest