name: Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+-dockerupdate-[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-dockerupdate-[0-9]+'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          buildx-version: latest
      - name: Build
        run: docker build --target=build -t languagetool-build .
      - name: Test
        run: docker run languagetool-build mvn --projects languagetool-standalone clean test --also-make --quiet
      - name: Tag
        run: |
          echo 'DOCKER_TAG<<EOF' >> $GITHUB_ENV
          echo $(echo ${{ github.ref }} | grep -oP '(?<=refs/tags/v).*') >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_ACCESSTOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin     
      - name: Push to Docker Hub
        run: |
          docker buildx build --push \
            --tag $DOCKERHUB_REPOSITORY:$DOCKER_TAG \
            --tag $DOCKERHUB_REPOSITORY:latest \
            --platform linux/amd64,linux/arm64 .
        env:
          DOCKERHUB_REPOSITORY: erikvl87/languagetool
      # - name: Push to GitHub Packages
      #   run: |
      #     docker tag languagetool docker.pkg.github.com/${{ github.repository }}/languagetool:$DOCKER_TAG
      #     docker tag languagetool docker.pkg.github.com/${{ github.repository }}/languagetool:latest
      #     docker login docker.pkg.github.com -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
      #     docker push docker.pkg.github.com/${{ github.repository }}/languagetool:$DOCKER_TAG