name: Tests

on:
  push:
    paths:
      - Dockerfile

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Download
      run: docker build --target=build -t languagetool-build .
    - name: Run tests
      run: docker run languagetool-build mvn --projects languagetool-standalone clean test --also-make --quiet